### ISSUE TITLE
Авторизация на клиенте

### ISSUE THREAD

**Issue by N0tilT** [ArkhamX2/Studenda#59]

**Comment by dubstepTractor** [comment]
а какая разница откуда запрос делать?

**Comment by N0tilT** [comment]
@dubstepTractor У нас есть какой-нибудь тестовый юзер в БД, за которого можно пытаться логиниться для теста?

Реализован ли механизм получения кода-пароля по почте? Или только сразу авторизация почта+пароль
Тогда нужно узнать какие юзеры есть уже и их пароль, чтобы для теста делать обращение с ними

**Comment by N0tilT** [comment]
@dubstepTractor 

По эндпоинту http://88.210.3.137/api/security/test статус 200, всё ок
Для юзера{"test@test.ru", "test", "student"}
register выдаёт 500 internal server error, видимо о несуществующей роли
login выдаёт 401 Unauthorized

Какие есть роли?
